# ${project.name}

Generated by **SpringGen** — Dynamic Backend Generator

## Tech Stack

- **Java** 17
- **Spring Boot** 3.2.5
- **Database**: ${project.databaseType!"H2"}
<#if project.securityEnabled>
- **Security**: ${project.securityType!"JWT"}
</#if>
<#if project.swaggerEnabled?? && project.swaggerEnabled>
- **API Docs**: Swagger UI (SpringDoc OpenAPI)
</#if>

## Getting Started

### Prerequisites

- Java 17+
- Maven 3.9+ (or use included Maven Wrapper)
<#if project.databaseType?? && project.databaseType == "POSTGRESQL">
- PostgreSQL 15+
<#elseif project.databaseType?? && project.databaseType == "MYSQL">
- MySQL 8+
</#if>

### Run

```bash
./mvnw spring-boot:run
```

### Build

```bash
./mvnw clean package
```

### API Documentation

<#if project.swaggerEnabled?? && project.swaggerEnabled>
After starting the application, visit: http://localhost:8080/swagger-ui.html
</#if>

## Project Structure

```
src/main/java/${project.packageName?replace(".", "/")}
├── controller/    # REST API endpoints
├── model/         # JPA entities
├── repository/    # Data access layer
├── service/       # Business logic interfaces
│   └── impl/      # Service implementations
├── dto/           # Data transfer objects
<#if project.securityEnabled>
├── config/        # Security configuration
├── security/      # JWT/Auth filters
</#if>
└── ${project.name?cap_first}Application.java
```

## Entities

<#list project.entities as entity>
- **${entity.name}** — ${entity.fields?size} fields
</#list>
